// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrlexnirncdnygfsptfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybGV4bmlybmNkbnlnZnNwdGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5ODA3OTksImV4cCI6MjA3NzU1Njc5OX0.8g4kQ7zkGx4FDVwz_BGAJj0Og-UabGfD8OkWv-Yfc6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});